//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormMain.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace= "http://yns/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace= "http://yns/", ConfigurationName="ServiceReference1.SimplexSoap")]
    public interface SimplexSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);

        // CODEGEN: Generating message contract since element name s from namespace http://yns/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/Concat", ReplyAction="*")]
        WinFormMain.ServiceReference1.ConcatResponse Concat(WinFormMain.ServiceReference1.ConcatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/Concat", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormMain.ServiceReference1.ConcatResponse> ConcatAsync(WinFormMain.ServiceReference1.ConcatRequest request);

        // CODEGEN: Generating message contract since element name a1 from namespace http://yns/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/Sum", ReplyAction="*")]
        WinFormMain.ServiceReference1.SumResponse Sum(WinFormMain.ServiceReference1.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormMain.ServiceReference1.SumResponse> SumAsync(WinFormMain.ServiceReference1.SumRequest request);

        // CODEGEN: Generating message contract since element name x from namespace http://yns/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/AddS", ReplyAction="*")]
        WinFormMain.ServiceReference1.AddSResponse AddS(WinFormMain.ServiceReference1.AddSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://yns/AddS", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormMain.ServiceReference1.AddSResponse> AddSAsync(WinFormMain.ServiceReference1.AddSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Concat", Namespace= "http://yns/", Order=0)]
        public WinFormMain.ServiceReference1.ConcatRequestBody Body;
        
        public ConcatRequest() {
        }
        
        public ConcatRequest(WinFormMain.ServiceReference1.ConcatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://yns/")]
    public partial class ConcatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double d;
        
        public ConcatRequestBody() {
        }
        
        public ConcatRequestBody(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConcatResponse", Namespace= "http://yns/", Order=0)]
        public WinFormMain.ServiceReference1.ConcatResponseBody Body;
        
        public ConcatResponse() {
        }
        
        public ConcatResponse(WinFormMain.ServiceReference1.ConcatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://yns/")]
    public partial class ConcatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConcatResult;
        
        public ConcatResponseBody() {
        }
        
        public ConcatResponseBody(string ConcatResult) {
            this.ConcatResult = ConcatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sum", Namespace= "http://yns/", Order=0)]
        public WinFormMain.ServiceReference1.SumRequestBody Body;
        
        public SumRequest() {
        }
        
        public SumRequest(WinFormMain.ServiceReference1.SumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://yns/")]
    public partial class SumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinFormMain.ServiceReference1.A a1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WinFormMain.ServiceReference1.A a2;
        
        public SumRequestBody() {
        }
        
        public SumRequestBody(WinFormMain.ServiceReference1.A a1, WinFormMain.ServiceReference1.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumResponse", Namespace= "http://yns/", Order=0)]
        public WinFormMain.ServiceReference1.SumResponseBody Body;
        
        public SumResponse() {
        }
        
        public SumResponse(WinFormMain.ServiceReference1.SumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://yns/")]
    public partial class SumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinFormMain.ServiceReference1.A SumResult;
        
        public SumResponseBody() {
        }
        
        public SumResponseBody(WinFormMain.ServiceReference1.A SumResult) {
            this.SumResult = SumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddS", Namespace= "http://yns/", Order=0)]
        public WinFormMain.ServiceReference1.AddSRequestBody Body;
        
        public AddSRequest() {
        }
        
        public AddSRequest(WinFormMain.ServiceReference1.AddSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://yns/")]
    public partial class AddSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string y;
        
        public AddSRequestBody() {
        }
        
        public AddSRequestBody(string x, string y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSResponse", Namespace= "http://yns/", Order=0)]
        public WinFormMain.ServiceReference1.AddSResponseBody Body;
        
        public AddSResponse() {
        }
        
        public AddSResponse(WinFormMain.ServiceReference1.AddSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace= "http://yns/")]
    public partial class AddSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSResult;
        
        public AddSResponseBody() {
        }
        
        public AddSResponseBody(string AddSResult) {
            this.AddSResult = AddSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : WinFormMain.ServiceReference1.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<WinFormMain.ServiceReference1.SimplexSoap>, WinFormMain.ServiceReference1.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormMain.ServiceReference1.ConcatResponse WinFormMain.ServiceReference1.SimplexSoap.Concat(WinFormMain.ServiceReference1.ConcatRequest request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            WinFormMain.ServiceReference1.ConcatRequest inValue = new WinFormMain.ServiceReference1.ConcatRequest();
            inValue.Body = new WinFormMain.ServiceReference1.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            WinFormMain.ServiceReference1.ConcatResponse retVal = ((WinFormMain.ServiceReference1.SimplexSoap)(this)).Concat(inValue);
            return retVal.Body.ConcatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormMain.ServiceReference1.ConcatResponse> WinFormMain.ServiceReference1.SimplexSoap.ConcatAsync(WinFormMain.ServiceReference1.ConcatRequest request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormMain.ServiceReference1.ConcatResponse> ConcatAsync(string s, double d) {
            WinFormMain.ServiceReference1.ConcatRequest inValue = new WinFormMain.ServiceReference1.ConcatRequest();
            inValue.Body = new WinFormMain.ServiceReference1.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            return ((WinFormMain.ServiceReference1.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormMain.ServiceReference1.SumResponse WinFormMain.ServiceReference1.SimplexSoap.Sum(WinFormMain.ServiceReference1.SumRequest request) {
            return base.Channel.Sum(request);
        }
        
        public WinFormMain.ServiceReference1.A Sum(WinFormMain.ServiceReference1.A a1, WinFormMain.ServiceReference1.A a2) {
            WinFormMain.ServiceReference1.SumRequest inValue = new WinFormMain.ServiceReference1.SumRequest();
            inValue.Body = new WinFormMain.ServiceReference1.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            WinFormMain.ServiceReference1.SumResponse retVal = ((WinFormMain.ServiceReference1.SimplexSoap)(this)).Sum(inValue);
            return retVal.Body.SumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormMain.ServiceReference1.SumResponse> WinFormMain.ServiceReference1.SimplexSoap.SumAsync(WinFormMain.ServiceReference1.SumRequest request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormMain.ServiceReference1.SumResponse> SumAsync(WinFormMain.ServiceReference1.A a1, WinFormMain.ServiceReference1.A a2) {
            WinFormMain.ServiceReference1.SumRequest inValue = new WinFormMain.ServiceReference1.SumRequest();
            inValue.Body = new WinFormMain.ServiceReference1.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            return ((WinFormMain.ServiceReference1.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormMain.ServiceReference1.AddSResponse WinFormMain.ServiceReference1.SimplexSoap.AddS(WinFormMain.ServiceReference1.AddSRequest request) {
            return base.Channel.AddS(request);
        }
        
        public string AddS(string x, string y) {
            WinFormMain.ServiceReference1.AddSRequest inValue = new WinFormMain.ServiceReference1.AddSRequest();
            inValue.Body = new WinFormMain.ServiceReference1.AddSRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            WinFormMain.ServiceReference1.AddSResponse retVal = ((WinFormMain.ServiceReference1.SimplexSoap)(this)).AddS(inValue);
            return retVal.Body.AddSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormMain.ServiceReference1.AddSResponse> WinFormMain.ServiceReference1.SimplexSoap.AddSAsync(WinFormMain.ServiceReference1.AddSRequest request) {
            return base.Channel.AddSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormMain.ServiceReference1.AddSResponse> AddSAsync(string x, string y) {
            WinFormMain.ServiceReference1.AddSRequest inValue = new WinFormMain.ServiceReference1.AddSRequest();
            inValue.Body = new WinFormMain.ServiceReference1.AddSRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((WinFormMain.ServiceReference1.SimplexSoap)(this)).AddSAsync(inValue);
        }
    }
}
